name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update GitHub Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update GitHub stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: 112Alex
          theme: transparent
          hide_border: false
          include_all_commits: false
          count_private: true
          layout: compact
          
      - name: Update GitHub streak
        uses: nirzak/github-readme-streak-stats@master
        with:
          user: 112Alex
          theme: transparent
          hide_border: false

      - name: Update Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: 112Alex
          theme: transparent
          hide_border: false
          include_all_commits: false
          count_private: true
          layout: compact

      - name: Commit and push
        uses: stefanzweck/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats"
          branch: main # Или master, если у вас так называется основная ветка
